package com.upm.subsystem;

import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import com.upm.subsystem.model.GenericResponse;
import com.upm.subsystem.model.Light;
import com.upm.subsystem.model.Temprature;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author
 */
public class TempratureController extends javax.swing.JFrame {

    /**
     * Creates new form LightController
     */
    public TempratureController() {
        initComponents();
        updateView();
    }

    public void updateView() {
        System.out.println("Update View Called");
      
         DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
         
        try {
            HttpResponse<GenericResponse> allDevices = Unirest.get(Utility.url+"temprature/getAllDevice")
                    .header("accept", "application/json")
                    .header("Content-Type", "application/json")
                    .asObject(GenericResponse.class);
            
             List  allDevs=(List)allDevices.getBody().getData();
             
               System.out.println("---- "+allDevs.size());
               
               for (Object allDev : allDevs) {
                   System.out.println("-------------- "+allDev.toString());
                   HashMap<String,String> dev=(HashMap<String,String>)allDev;
                 
                 tableModel.addRow(new String[]{dev.get("deviceId"),dev.get("roomName"), dev.get("temprature"), dev.get("time")});
                  
            }
                tableModel.fireTableDataChanged();
            
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
        
       

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();
        updateTempBtn = new javax.swing.JButton();
        removeDevBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 51));
        jLabel1.setText("Control Room Temprature");

        addButton.setBackground(new java.awt.Color(255, 255, 255));
        addButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addButton.setForeground(new java.awt.Color(0, 204, 51));
        addButton.setText("Add Temprature Device");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        updateTempBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updateTempBtn.setForeground(new java.awt.Color(0, 102, 255));
        updateTempBtn.setText("Update Temprature");
        updateTempBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateTempBtnActionPerformed(evt);
            }
        });

        removeDevBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        removeDevBtn.setForeground(new java.awt.Color(255, 0, 0));
        removeDevBtn.setText("Remove Device");
        removeDevBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeDevBtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Device Id");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Room Name");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Temprature");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(updateTempBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(removeDevBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addButton)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                        .addComponent(jTextField2)
                        .addComponent(jTextField3)))
                .addContainerGap(261, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateTempBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeDevBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Device ID", "Room Name", "Current Temprature", "Time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 722, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed

        // Validation
        if(jTextField1.getText()== null || jTextField1.getText().isEmpty()){
             JOptionPane.showMessageDialog(rootPane, "Device Id can't be blank");
             return ;
        }
        
          if(jTextField2.getText()== null || jTextField2.getText().isEmpty()){
             JOptionPane.showMessageDialog(rootPane, "Room name can't be null");
             return ;
        }
           if(jTextField3.getText()== null || jTextField3.getText().isEmpty()){
             JOptionPane.showMessageDialog(rootPane, "Temprature can't be null");
             return ;
        }
        
        Temprature temp = new Temprature();
        temp.setDeviceId(jTextField1.getText());
        temp.setRoomName(jTextField2.getText());
        temp.setTemprature(jTextField3.getText());
        temp.setTime(new Date().toString());
        try {
            HttpResponse<GenericResponse> postResponse = Unirest.post(Utility.url+"temprature/addDevice")
                    .header("accept", "application/json")
                    .header("Content-Type", "application/json")
                    .body(temp)
                    .asObject(GenericResponse.class);
            
            JOptionPane.showMessageDialog(rootPane, postResponse.getBody().getMessage());
           // Update row in table
           DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
            tableModel.addRow(new String[]{temp.getDeviceId(),temp.getRoomName(), temp.getTemprature(), temp.getTime()});
           tableModel.fireTableDataChanged();  
           // set the data to blank
           jTextField1.setText("");
           jTextField2.setText("");
           jTextField3.setText("");
           
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }

    }//GEN-LAST:event_addButtonActionPerformed

    private void updateTempBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateTempBtnActionPerformed
        
          try {
                int rowIndex=jTable1.getSelectedRow();
                DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
              String deviceId=(String) tableModel.getValueAt(rowIndex, 0);
              
              String newTemp=jTextField3.getText();
              Temprature temp=new Temprature();
              temp.setDeviceId(deviceId);
              temp.setTemprature(newTemp);
                        
            HttpResponse<GenericResponse> postResponse = Unirest.post(Utility.url+"temprature/updateTemprature/")
                    .header("accept", "application/json")
                    .header("Content-Type", "application/json")
                    .body(temp)
                    .asObject(GenericResponse.class);
            JOptionPane.showMessageDialog(rootPane, postResponse.getBody().getMessage());
           // Update row in table
          tableModel.setValueAt(newTemp, rowIndex,2);
          tableModel.fireTableDataChanged();
               
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
        
    }//GEN-LAST:event_updateTempBtnActionPerformed

    private void removeDevBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeDevBtnActionPerformed
        try {
                int rowIndex=jTable1.getSelectedRow();
                 DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
              String deviceId=(String) tableModel.getValueAt(rowIndex, 0);
              System.out.println("-- Device Id "+deviceId);
                        
            HttpResponse<GenericResponse> postResponse = Unirest.delete(Utility.url+"temprature/removeDevice/"+deviceId)
                    .header("accept", "application/json")
                    .header("Content-Type", "application/json")
                    .asObject(GenericResponse.class);
            JOptionPane.showMessageDialog(rootPane, postResponse.getBody().getMessage());
           // Update row in table
         tableModel.removeRow(rowIndex);
          tableModel.fireTableDataChanged();
               
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }//GEN-LAST:event_removeDevBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JButton removeDevBtn;
    private javax.swing.JButton updateTempBtn;
    // End of variables declaration//GEN-END:variables
}
